### PR TITLE
refactor: updating the transfer to allow death as new on chain logic

### PR DESCRIPTION
**Pull request by Dudleyneedham**
Balances pallet now uses transfer allow death or transfer keep alive. 

We will use the allow death.

### CODE REVIEW

**Comment by Dudleyneedham** [comment]
Currently this works only on the staging.

**Review by arty-name — APPROVED** [review]
Looks good, but do you also want to drop the warnings about the existential limit?

**Comment by rflechtner** [comment]
> Currently this works only on the staging.

That would be a problem, but I also don't think it's true - transferAllowDeath currently already exists on spiritnet.

**Comment by Dudleyneedham** [comment]
I checked and currently `transferAllowDeath` is on the spiritnet. My assumption was false, as per Raphael's remarks.

**Pull request merged**
